local M = {}

function M.setup()
	local harpoon = require("harpoon")
	harpoon:setup()

	vim.keymap.set("n", "<leader>a", function()
		harpoon:list():add()
	end, { desc = "Add file to harpoon", silent = true })
	vim.keymap.set("n", "<leader>hm", function()
		harpoon.ui:toggle_quick_menu(harpoon:list())
	end, { desc = "Toggle harpoon menu", silent = true })
	vim.keymap.set("n", "<leader>1", function()
		harpoon:list():select(1)
	end, { desc = "Harpoon file 1", silent = true })
	vim.keymap.set("n", "<leader>2", function()
		harpoon:list():select(2)
	end, { desc = "Harpoon file 2", silent = true })
	vim.keymap.set("n", "<leader>3", function()
		harpoon:list():select(3)
	end, { desc = "Harpoon file 3", silent = true })
	vim.keymap.set("n", "<leader>4", function()
		harpoon:list():select(4)
	end, { desc = "Harpoon file 4", silent = true })
	vim.keymap.set("n", "<C-S-P>", function()
		harpoon:list():prev()
	end, { desc = "Previous harpoon file", silent = true })
	vim.keymap.set("n", "<C-S-N>", function()
		harpoon:list():next()
	end, { desc = "Next harpoon file", silent = true })
	vim.keymap.set("n", "<leader>ha", function()
		harpoon:list():add()
	end, { desc = "Add file to harpoon", silent = true })
	vim.keymap.set("n", "<leader>hr", function()
		harpoon:list():remove()
	end, { desc = "Remove file from harpoon", silent = true })
	vim.keymap.set("n", "<leader>hc", function()
		harpoon:list():clear()
	end, { desc = "Clear harpoon list", silent = true })
end

return M
